In [13]:
import pandas as pd
import numpy as np
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich import box
from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import LabelEncoder

In [2]:
# load dataset
pd.set_option('display.max_columns', None)
data = pd.read_csv('Dataset/dataset_clean.csv')

In [3]:
COLOR_DARK_NAVY = "#333F6E"
COLOR_BLUE_GREY = "#869EAF"
COLOR_BEIGE = "#DFD097"
COLOR_CREAM = "#CECEAB"
 

HTML_OUTPUT_PATH = "Report/hr_summary_report.html"
 
 
# record_console=True lets us export everything printed to HTML afterwards
console = Console(record=True)
 
# ---- Age statistics panel ----
age_stats = data['age'].agg(['min', 'mean', 'max'])
age_stats['mean'] = age_stats['mean'].round(1)
 
age_table = Table(
    title="📈 Age Statistics",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
 
age_table.add_column("Measure", style=COLOR_BLUE_GREY)
age_table.add_column("Value", style=COLOR_BEIGE, justify="right")
 
age_table.add_row("Minimum", f"{age_stats['min']} years")
age_table.add_row("Mean", f"{age_stats['mean']} years")
age_table.add_row("Maximum", f"{age_stats['max']} years")
 
# ---- Gender distribution table ----
gender_counts = data['gender'].value_counts()
gender_pcts = data['gender'].value_counts(normalize=True) * 100
 
gender_table = Table(
    title="📊 Gender Distribution",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
 
gender_table.add_column("Gender", style=COLOR_BLUE_GREY)
gender_table.add_column("Count", style=COLOR_BEIGE, justify="right")
gender_table.add_column("Percentage", style=COLOR_CREAM, justify="right")
 
for gender, count in gender_counts.items():
    gender_table.add_row(gender, f"{count:,}", f"{gender_pcts[gender]:.1f}%")
 
# ---- Role distribution table ----
role_counts = data['role'].value_counts()
role_pcts = data['role'].value_counts(normalize=True) * 100
 
role_table = Table(
    title="💼 Role Distribution",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
 
role_table.add_column("Role", style=COLOR_BLUE_GREY)
role_table.add_column("Count", style=COLOR_BEIGE, justify="right")
role_table.add_column("Percentage", style=COLOR_CREAM, justify="right")
 
for role, count in role_counts.head(10).items():  # Show top 10 roles
    role_table.add_row(role, f"{count:,}", f"{role_pcts[role]:.1f}%")
 
# ---- Years in company statistics panel ----
tenure_stats = data['years_in_company'].agg(['min', 'mean', 'max'])
tenure_stats['mean'] = tenure_stats['mean'].round(1)
 
tenure_table = Table(
    title="🏢 Years in Company",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
 
tenure_table.add_column("Measure", style=COLOR_BLUE_GREY)
tenure_table.add_column("Value", style=COLOR_BEIGE, justify="right")
 
tenure_table.add_row("Minimum", f"{tenure_stats['min']} years")
tenure_table.add_row("Mean", f"{tenure_stats['mean']} years")
tenure_table.add_row("Maximum", f"{tenure_stats['max']} years")
 
# ---- Hours worked per week statistics panel ----
hours_stats = data['hours_worked_per_week'].agg(['min', 'mean', 'max'])
hours_stats['mean'] = hours_stats['mean'].round(1)
 
hours_table = Table(
    title="⏱️ Hours Worked per Week",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
 
hours_table.add_column("Measure", style=COLOR_BLUE_GREY)
hours_table.add_column("Value", style=COLOR_BEIGE, justify="right")
 
hours_table.add_row("Minimum", f"{hours_stats['min']} hrs")
hours_table.add_row("Mean", f"{hours_stats['mean']} hrs")
hours_table.add_row("Maximum", f"{hours_stats['max']} hrs")
 
# ---- Monthly salary statistics panel ----
salary_stats = data['monthly_salary_usd'].agg(['min', 'mean', 'max'])
salary_stats['mean'] = salary_stats['mean'].round(1)
 
salary_table = Table(
    title="💰 Monthly Salary (USD)",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
 
salary_table.add_column("Measure", style=COLOR_BLUE_GREY)
salary_table.add_column("Value", style=COLOR_BEIGE, justify="right")
 
salary_table.add_row("Minimum", f"${salary_stats['min']:,.0f}")
salary_table.add_row("Mean", f"${salary_stats['mean']:,.0f}")
salary_table.add_row("Maximum", f"${salary_stats['max']:,.0f}")
 
# ---- Burnout risk distribution table ----
burnout_counts = data['burnout_risk'].value_counts()
burnout_pcts = data['burnout_risk'].value_counts(normalize=True) * 100
 
burnout_table = Table(
    title="🔥 Burnout Risk Distribution",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
 
burnout_table.add_column("Burnout Risk", style=COLOR_BLUE_GREY)
burnout_table.add_column("Count", style=COLOR_BEIGE, justify="right")
burnout_table.add_column("Percentage", style=COLOR_CREAM, justify="right")
 
for risk, count in burnout_counts.items():
    burnout_table.add_row(risk, f"{count:,}", f"{burnout_pcts[risk]:.1f}%")
 
# ---- Work mode distribution table ----
work_mode_counts = data['work_mode'].value_counts()
work_mode_pcts = data['work_mode'].value_counts(normalize=True) * 100
 
work_mode_table = Table(
    title="🏠 Work Mode Distribution",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
 
work_mode_table.add_column("Work Mode", style=COLOR_BLUE_GREY)
work_mode_table.add_column("Count", style=COLOR_BEIGE, justify="right")
work_mode_table.add_column("Percentage", style=COLOR_CREAM, justify="right")
 
for mode, count in work_mode_counts.items():
    work_mode_table.add_row(mode, f"{count:,}", f"{work_mode_pcts[mode]:.1f}%")
 
# ---- Display all tables ----
console.print(age_table)
console.print(gender_table)
console.print(role_table)
console.print(tenure_table)
console.print(hours_table)
console.print(salary_table)
console.print(burnout_table)
console.print(work_mode_table)
 
# ---- Summary panel ----
console.print(Panel(
    f"[bold {COLOR_CREAM}]Total Employees:[/bold {COLOR_CREAM}] {len(data):,}\n"
    f"[bold {COLOR_CREAM}]Age Range:[/bold {COLOR_CREAM}] {age_stats['min']} - {age_stats['max']} years\n"
    f"[bold {COLOR_CREAM}]Most Common Gender:[/bold {COLOR_CREAM}] {gender_counts.index[0]}\n"
    f"[bold {COLOR_CREAM}]Most Common Role:[/bold {COLOR_CREAM}] {role_counts.index[0]} ({role_pcts.iloc[0]:.1f}%)\n"
    f"[bold {COLOR_CREAM}]Average Tenure:[/bold {COLOR_CREAM}] {tenure_stats['mean']} years\n"
    f"[bold {COLOR_CREAM}]Average Hours/Week:[/bold {COLOR_CREAM}] {hours_stats['mean']} hrs\n"
    f"[bold {COLOR_CREAM}]Average Salary:[/bold {COLOR_CREAM}] ${salary_stats['mean']:,.0f}\n"
    f"[bold {COLOR_CREAM}]Most Common Burnout Risk:[/bold {COLOR_CREAM}] {burnout_counts.index[0]} ({burnout_pcts.iloc[0]:.1f}%)\n"
    f"[bold {COLOR_CREAM}]Most Common Work Mode:[/bold {COLOR_CREAM}] {work_mode_counts.index[0]} ({work_mode_pcts.iloc[0]:.1f}%)",
    title="Summary",
    border_style=COLOR_BEIGE
))
 
# ---- Export to HTML with black background + custom theme ----
console.save_html(
    HTML_OUTPUT_PATH,
    theme=None,  # we override styling manually below for full control
    inline_styles=True
)
 

with open(HTML_OUTPUT_PATH, "r", encoding="utf-8") as f:
    html_content = f.read()
 
html_content = html_content.replace(
    "body {\n    color: #000000;\n    background-color: #ffffff;\n}",
    f"body {{\n    color: {COLOR_CREAM};\n    background-color: #000000;\n}}"
)
 
# Force black background on <body> (and the pre/code block rich wraps output in)
html_content = html_content.replace(
    "<body>",
    f'<body style="background-color:#000000; margin:0; padding:20px;">'
)
 
with open(HTML_OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(html_content)
 
print(f"\nSaved HTML report")

   📈 Age Statistics

  Measure        Value
 ──────────────────────
  Minimum   22.0 years
  Mean      41.0 years
  Maximum   60.0 years

       📊 Gender Distribution

  Gender        Count   Percentage
 ──────────────────────────────────
  Male         11,900        47.6%
  Female       11,878        47.5%
  Non-binary    1,222         4.9%

       💼 Role Distribution

  Role        Count   Percentage
 ────────────────────────────────
  Support     5,912        23.6%
  Developer   4,588        18.4%
  Sales       4,481        17.9%
  Manager     4,164        16.7%
  HR          3,795        15.2%
  Executive   2,060         8.2%

  🏢 Years in Company

  Measure        Value
 ──────────────────────
  Minimum    0.0 years
  Mean       9.0 years
  Maximum   42.0 years

  ⏱️ Hours Worked per
         Week

  Measure      Value
 ────────────────────
  Minimum   35.0 hrs
  Mean      46.2 hrs
  Maximum   70.0 hrs

  💰 Monthly Salary
        (USD)

  Measure     Value
 ───────────────────
  Minimum    $2,500
  Mean       $8,181
  Maximum   $19,450

     🔥 Burnout Risk Distribution

  Burnout Risk    Count   Percentage
 ────────────────────────────────────
  Moderate       16,500        66.0%
  Low             4,500        18.0%
  High            4,000        16.0%

    🏠 Work Mode Distribution

  Work Mode   Count   Percentage
 ────────────────────────────────
  Hybrid      9,722        38.9%
  Remote      9,288        37.2%
  On-site     5,990        24.0%

╭──────────────────────────────────────────────────── Summary ────────────────────────────────────────────────────╮
│ Total Employees: 25,000                                                                                         │
│ Age Range: 22.0 - 60.0 years                                                                                    │
│ Most Common Gender: Male                                                                                        │
│ Most Common Role: Support (23.6%)                                                                               │
│ Average Tenure: 9.0 years                                                                                       │
│ Average Hours/Week: 46.2 hrs                                                                                    │
│ Average Salary: $8,181                                                                                          │
│ Most Common Burnout Risk: Moderate (66.0%)                                                                      │
│ Most Common Work Mode: Hybrid (38.9%)                                                                           │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Saved HTML report

In [4]:
COLOR_DARK_NAVY = "#333F6E"
COLOR_BLUE_GREY = "#869EAF"
COLOR_BEIGE = "#DFD097"
COLOR_CREAM = "#CECEAB"

HTML_OUTPUT_PATH = "Report/wellbeing_workload_analysis.html"

 
console = Console(record=True)
 
# ---- Column groups ----
# Scores on a bounded scale (1-5, or 0-10 for anxiety/depression)
WELLBEING_SCORES = {
    "Work-Life Balance": "work_life_balance_score",
    "Job Satisfaction": "job_satisfaction_score",
    "Stress Level (self-report)": "stress_level_self_report",
    "Anxiety Score": "anxiety_score",
    "Depression Score": "depression_score",
    "Sleep Quality": "sleep_quality_score",
    "Social Support": "social_support_score",
    "Manager Support": "manager_support_score",
}
 
# Workload-related measures (time/frequency based, not bounded scores)
WORKLOAD_MEASURES = {
    "Commute Time (mins)": "commute_time_mins",
    "Absenteeism (days/month)": "absenteeism_days_per_month",
    "Overtime (hrs/week)": "overtime_hours_per_week",
    "Workload Index": "workload_index",
}
 
 
# 1. Wellbeing scores — Min / Mean / Max

wellbeing_table = Table(
    title="🧠 Wellbeing Scores — Overview",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
wellbeing_table.add_column("Indicator", style=COLOR_BLUE_GREY)
wellbeing_table.add_column("Min", style=COLOR_BEIGE, justify="right")
wellbeing_table.add_column("Mean", style=COLOR_CREAM, justify="right")
wellbeing_table.add_column("Max", style=COLOR_BEIGE, justify="right")
 
for label, col in WELLBEING_SCORES.items():
    stats = data[col].agg(['min', 'mean', 'max'])
    wellbeing_table.add_row(label, f"{stats['min']:.1f}", f"{stats['mean']:.2f}", f"{stats['max']:.1f}")
 
 
# 2. Workload measures — Min / Mean / Max

workload_table = Table(
    title="⏱️ Workload Measures — Overview",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
workload_table.add_column("Indicator", style=COLOR_BLUE_GREY)
workload_table.add_column("Min", style=COLOR_BEIGE, justify="right")
workload_table.add_column("Mean", style=COLOR_CREAM, justify="right")
workload_table.add_column("Max", style=COLOR_BEIGE, justify="right")
 
for label, col in WORKLOAD_MEASURES.items():
    stats = data[col].agg(['min', 'mean', 'max'])
    workload_table.add_row(label, f"{stats['min']:.1f}", f"{stats['mean']:.2f}", f"{stats['max']:.1f}")
 

# 3. Mental health benefit utilization — distribution
 
benefit_counts = data['mental_health_benefit_utilized'].value_counts()
benefit_pcts = data['mental_health_benefit_utilized'].value_counts(normalize=True) * 100
benefit_labels = {0: "Not Utilized", 1: "Utilized"}
 
benefit_table = Table(
    title="🩺 Mental Health Benefit Utilization",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
benefit_table.add_column("Status", style=COLOR_BLUE_GREY)
benefit_table.add_column("Count", style=COLOR_BEIGE, justify="right")
benefit_table.add_column("Percentage", style=COLOR_CREAM, justify="right")
 
for value, count in benefit_counts.items():
    benefit_table.add_row(benefit_labels.get(value, str(value)), f"{count:,}", f"{benefit_pcts[value]:.1f}%")
 

# 4. Scores by benefit utilization (Used vs Not Used)
benefit_compare_table = Table(
    title="🔍 Wellbeing Scores by Benefit Utilization",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
benefit_compare_table.add_column("Indicator", style=COLOR_BLUE_GREY)
benefit_compare_table.add_column("Not Utilized", style=COLOR_BEIGE, justify="right")
benefit_compare_table.add_column("Utilized", style=COLOR_CREAM, justify="right")
benefit_compare_table.add_column("Difference", style=COLOR_BEIGE, justify="right")
 
compare_cols = {**WELLBEING_SCORES, "Workload Index": "workload_index"}
for label, col in compare_cols.items():
    grouped = data.groupby('mental_health_benefit_utilized')[col].mean()
    not_used = grouped.get(0, float('nan'))
    used = grouped.get(1, float('nan'))
    diff = used - not_used
    sign = "+" if diff >= 0 else ""
    benefit_compare_table.add_row(label, f"{not_used:.2f}", f"{used:.2f}", f"{sign}{diff:.2f}")
 
 
# 5. Workload & wellbeing by burnout risk level
#    This answers: how do these indicators change as burnout risk rises?

burnout_order = ["Low", "Moderate", "High"]
burnout_table = Table(
    title="🔥 Key Indicators by Burnout Risk",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
burnout_table.add_column("Indicator", style=COLOR_BLUE_GREY)
burnout_table.add_column("Low Risk", style=COLOR_BEIGE, justify="right")
burnout_table.add_column("Moderate Risk", style=COLOR_CREAM, justify="right")
burnout_table.add_column("High Risk", style=COLOR_BEIGE, justify="right")
 
burnout_rows = {
    "Workload Index": "workload_index",
    "Stress Level (self-report)": "stress_level_self_report",
    "Overtime (hrs/week)": "overtime_hours_per_week",
    "Work-Life Balance": "work_life_balance_score",
    "Sleep Quality": "sleep_quality_score",
}
for label, col in burnout_rows.items():
    grouped = data.groupby('burnout_risk')[col].mean()
    burnout_table.add_row(
        label,
        f"{grouped.get('Low', float('nan')):.2f}",
        f"{grouped.get('Moderate', float('nan')):.2f}",
        f"{grouped.get('High', float('nan')):.2f}",
    )
 
# ---- Display all tables ----
console.print(wellbeing_table)
console.print(workload_table)
console.print(benefit_table)
console.print(benefit_compare_table)
console.print(burnout_table)
 
# ---- Summary panel ----
highest_diff_label, highest_diff_col = max(
    compare_cols.items(),
    key=lambda item: abs(
        data.groupby('mental_health_benefit_utilized')[item[1]].mean().diff().iloc[-1]
    )
)
 
console.print(Panel(
    f"[bold {COLOR_CREAM}]Avg Stress Level:[/bold {COLOR_CREAM}] {data['stress_level_self_report'].mean():.2f} / 5\n"
    f"[bold {COLOR_CREAM}]Avg Anxiety Score:[/bold {COLOR_CREAM}] {data['anxiety_score'].mean():.2f} / 10\n"
    f"[bold {COLOR_CREAM}]Avg Depression Score:[/bold {COLOR_CREAM}] {data['depression_score'].mean():.2f} / 10\n"
    f"[bold {COLOR_CREAM}]Avg Workload Index:[/bold {COLOR_CREAM}] {data['workload_index'].mean():.2f} / 10\n"
    f"[bold {COLOR_CREAM}]Mental Health Benefit Used:[/bold {COLOR_CREAM}] {benefit_pcts.get(1, 0):.1f}%\n"
    f"[bold {COLOR_CREAM}]Workload Index — High vs Low Burnout:[/bold {COLOR_CREAM}] "
    f"{data.groupby('burnout_risk')['workload_index'].mean().get('High', 0):.2f} vs "
    f"{data.groupby('burnout_risk')['workload_index'].mean().get('Low', 0):.2f}\n"
    f"[bold {COLOR_CREAM}]Largest Gap by Benefit Use:[/bold {COLOR_CREAM}] {highest_diff_label}",
    title="📊 Wellbeing & Workload Summary",
    border_style=COLOR_BEIGE
))
 
# ---- Export to HTML with black background + custom theme ----
console.save_html(
    HTML_OUTPUT_PATH,
    theme=None,
    inline_styles=True
)
 
with open(HTML_OUTPUT_PATH, "r", encoding="utf-8") as f:
    html_content = f.read()
 
html_content = html_content.replace(
    "body {\n    color: #000000;\n    background-color: #ffffff;\n}",
    f"body {{\n    color: {COLOR_CREAM};\n    background-color: #000000;\n}}"
)
html_content = html_content.replace(
    "<body>",
    '<body style="background-color:#000000; margin:0; padding:20px;">'
)
 
with open(HTML_OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(html_content)
 
print(f"\nSaved HTML report")

          🧠 Wellbeing Scores — Overview

  Indicator                    Min   Mean    Max
 ────────────────────────────────────────────────
  Work-Life Balance            1.0   3.79    5.0
  Job Satisfaction             1.0   3.78    5.0
  Stress Level (self-report)   1.0   2.36    5.0
  Anxiety Score                0.0   3.55   10.0
  Depression Score             0.0   2.88    9.2
  Sleep Quality                1.0   3.79    5.0
  Social Support               1.0   3.27    5.0
  Manager Support              1.0   3.42    5.0

          ⏱️ Workload Measures — Overview

  Indicator                  Min    Mean     Max
 ────────────────────────────────────────────────
  Commute Time (mins)        0.0   25.37   118.0
  Absenteeism (days/month)   0.0    0.91     6.0
  Overtime (hrs/week)        0.0    1.75    25.0
  Workload Index             0.0    3.85    10.0

 🩺 Mental Health Benefit Utilization

  Status          Count   Percentage
 ────────────────────────────────────
  Not Utilized   19,033        76.1%
  Utilized        5,967        23.9%

             🔍 Wellbeing Scores by Benefit Utilization

  Indicator                    Not Utilized   Utilized   Difference
 ───────────────────────────────────────────────────────────────────
  Work-Life Balance                    3.82       3.73        -0.09
  Job Satisfaction                     3.80       3.74        -0.06
  Stress Level (self-report)           2.27       2.66        +0.38
  Anxiety Score                        3.49       3.77        +0.29
  Depression Score                     2.83       3.06        +0.23
  Sleep Quality                        3.81       3.73        -0.08
  Social Support                       3.28       3.24        -0.04
  Manager Support                      3.42       3.42        -0.01
  Workload Index                       3.80       4.02        +0.22

                  🔥 Key Indicators by Burnout Risk

  Indicator                    Low Risk   Moderate Risk   High Risk
 ───────────────────────────────────────────────────────────────────
  Workload Index                   2.89            3.84        4.97
  Stress Level (self-report)       1.74            2.35        3.10
  Overtime (hrs/week)              0.52            1.53        4.08
  Work-Life Balance                4.14            3.80        3.40
  Sleep Quality                    4.07            3.79        3.47

╭──────────────────────────────────────── 📊 Wellbeing & Workload Summary ────────────────────────────────────────╮
│ Avg Stress Level: 2.36 / 5                                                                                      │
│ Avg Anxiety Score: 3.55 / 10                                                                                    │
│ Avg Depression Score: 2.88 / 10                                                                                 │
│ Avg Workload Index: 3.85 / 10                                                                                   │
│ Mental Health Benefit Used: 23.9%                                                                               │
│ Workload Index — High vs Low Burnout: 4.97 vs 2.89                                                              │
│ Largest Gap by Benefit Use: Stress Level (self-report)                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Saved HTML report

In [5]:
# Age group
bins = [ 20, 30,40, 50, 60, 200]
labels = ['20-29', '30-39', '40-49', '50-59', '60+']
data['Age_group'] = pd.cut(data['age'], bins=bins, labels=labels, right=False)

print(data['Age_group'].value_counts().sort_index())

Age_group
20-29    5122
30-39    6415
40-49    6431
50-59    6385
60+       647
Name: count, dtype: int64

In [6]:
data.groupby('burnout_risk')['Age_group'].value_counts()

burnout_risk  Age_group
High          40-49        1079
              50-59        1036
              30-39        1005
              20-29         777
              60+           103
Low           30-39        1171
              40-49        1156
              50-59        1114
              20-29         951
              60+           108
Moderate      30-39        4239
              50-59        4235
              40-49        4196
              20-29        3394
              60+           436
Name: count, dtype: int64

In [7]:
data.sample()

,employee_id,age,gender,role,years_in_company,hours_worked_per_week,work_life_balance_score,job_satisfaction_score,stress_level_self_report,anxiety_score,depression_score,sleep_quality_score,social_support_score,presenteeism_days_per_month,burnout_risk,left_company_last_year,work_mode,commute_time_mins,monthly_salary_usd,manager_support_score,workload_index,vacation_days_taken,years_since_last_promotion,absenteeism_days_per_month,overtime_hours_per_week,mental_health_benefit_utilized,Age_group
22814,22815,35,Male,Developer,9,51,5.0,2.7,4.5,6.7,3.0,4.3,2.4,1,Moderate,0,Remote,0,8650.0,2.2,3.8,14,4.0,2,4,1,30-39

In [9]:
# burnout_risk is text (Low/Moderate/High), so we first convert it to an
# ordered number before we can correlate it with other numeric columns
risk_map = {'Low': 0, 'Moderate': 1, 'High': 2}
data['burnout_risk_numeric'] = data['burnout_risk'].map(risk_map)

numeric_cols = data.select_dtypes(include='number').columns.drop(['employee_id', 'burnout_risk_numeric'])

correlations = data[numeric_cols].corrwith(data['burnout_risk_numeric']).sort_values(ascending=False)
print(correlations.round(3))

stress_level_self_report          0.480
workload_index                    0.439
hours_worked_per_week             0.406
overtime_hours_per_week           0.288
anxiety_score                     0.242
depression_score                  0.143
monthly_salary_usd                0.109
commute_time_mins                 0.104
presenteeism_days_per_month       0.100
mental_health_benefit_utilized    0.100
left_company_last_year            0.099
absenteeism_days_per_month        0.066
years_in_company                  0.039
years_since_last_promotion        0.031
age                               0.015
social_support_score             -0.022
vacation_days_taken              -0.050
manager_support_score            -0.086
job_satisfaction_score           -0.143
sleep_quality_score              -0.234
work_life_balance_score          -0.310
dtype: float64

In [11]:
COLOR_DARK_NAVY = "#333F6E"
COLOR_BLUE_GREY = "#869EAF"
COLOR_BEIGE = "#A1E197"     # used for positive correlation (raises risk)
COLOR_CREAM = "#E08D8D"     # used for negative correlation (lowers risk)

 
HTML_OUTPUT_PATH = "Report/burnout_correlation_analysis.html"
 
 
console = Console(record=True)
 
# ---- Build the ordered numeric version of burnout_risk ----
risk_map = {'Low': 0, 'Moderate': 1, 'High': 2}
data['burnout_risk_numeric'] = data['burnout_risk'].map(risk_map)
 
numeric_cols = data.select_dtypes(include='number').columns.drop(
    ['employee_id', 'burnout_risk_numeric']
)
correlations = data[numeric_cols].corrwith(data['burnout_risk_numeric']).sort_values(ascending=False)
 
# ---- Human-readable labels for each column ----
LABELS = {
    "stress_level_self_report": "Stress Level (self-report)",
    "workload_index": "Workload Index",
    "hours_worked_per_week": "Hours Worked per Week",
    "overtime_hours_per_week": "Overtime (hrs/week)",
    "anxiety_score": "Anxiety Score",
    "depression_score": "Depression Score",
    "monthly_salary_usd": "Monthly Salary",
    "commute_time_mins": "Commute Time",
    "presenteeism_days_per_month": "Presenteeism (days/month)",
    "mental_health_benefit_utilized": "Mental Health Benefit Used",
    "left_company_last_year": "Left Company Last Year",
    "absenteeism_days_per_month": "Absenteeism (days/month)",
    "years_in_company": "Years in Company",
    "years_since_last_promotion": "Years Since Last Promotion",
    "age": "Age",
    "social_support_score": "Social Support",
    "vacation_days_taken": "Vacation Days Taken",
    "manager_support_score": "Manager Support",
    "job_satisfaction_score": "Job Satisfaction",
    "sleep_quality_score": "Sleep Quality",
    "work_life_balance_score": "Work-Life Balance",
}
 
 
def strength_label(value: float) -> str:
    """Simple qualitative read of correlation strength."""
    abs_v = abs(value)
    if abs_v >= 0.4:
        return "Strong"
    if abs_v >= 0.2:
        return "Moderate"
    if abs_v >= 0.1:
        return "Weak"
    return "Negligible"
 
 
# ---- Correlation table ----
corr_table = Table(
    title="🔗 Correlation with Burnout Risk",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)
corr_table.add_column("Factor", style=COLOR_BLUE_GREY)
corr_table.add_column("Correlation", justify="right")
corr_table.add_column("Strength", justify="center")
 
for col, value in correlations.items():
    label = LABELS.get(col, col)
    color = COLOR_BEIGE if value >= 0 else COLOR_CREAM
    corr_table.add_row(
        label,
        f"[{color}]{value:+.3f}[/{color}]",
        strength_label(value),
    )
 
console.print(corr_table)
 
# ---- Summary panel ----
top_risk_factor = correlations.index[0]
top_protective_factor = correlations.index[-1]
 
console.print(Panel(
    f"[bold {COLOR_BEIGE}]Strongest Risk Factor:[/bold {COLOR_BEIGE}] "
    f"{LABELS.get(top_risk_factor, top_risk_factor)} ({correlations[top_risk_factor]:+.3f})\n"
    f"[bold {COLOR_CREAM}]Strongest Protective Factor:[/bold {COLOR_CREAM}] "
    f"{LABELS.get(top_protective_factor, top_protective_factor)} ({correlations[top_protective_factor]:+.3f})\n"
    f"[bold {COLOR_BLUE_GREY}]Top 3 Risk Drivers:[/bold {COLOR_BLUE_GREY}] "
    + ", ".join(LABELS.get(c, c) for c in correlations.head(3).index) + "\n"
    f"[bold {COLOR_BLUE_GREY}]Top 3 Protective Factors:[/bold {COLOR_BLUE_GREY}] "
    + ", ".join(LABELS.get(c, c) for c in correlations.tail(3).index),
    title="📊 Key Takeaways",
    border_style=COLOR_DARK_NAVY
))
 
# ---- Export to HTML with black background + custom theme ----
console.save_html(
    HTML_OUTPUT_PATH,
    theme=None,
    inline_styles=True
)
 
with open(HTML_OUTPUT_PATH, "r", encoding="utf-8") as f:
    html_content = f.read()
 
html_content = html_content.replace(
    "body {\n    color: #000000;\n    background-color: #ffffff;\n}",
    f"body {{\n    color: {COLOR_CREAM};\n    background-color: #000000;\n}}"
)
html_content = html_content.replace(
    "<body>",
    '<body style="background-color:#000000; margin:0; padding:20px;">'
)
 
with open(HTML_OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(html_content)
 
print(f"\nSaved HTML report")

            🔗 Correlation with Burnout Risk

  Factor                       Correlation    Strength
 ───────────────────────────────────────────────────────
  Stress Level (self-report)        +0.480     Strong
  Workload Index                    +0.439     Strong
  Hours Worked per Week             +0.406     Strong
  Overtime (hrs/week)               +0.288    Moderate
  Anxiety Score                     +0.242    Moderate
  Depression Score                  +0.143      Weak
  Monthly Salary                    +0.109      Weak
  Commute Time                      +0.104      Weak
  Presenteeism (days/month)         +0.100      Weak
  Mental Health Benefit Used        +0.100   Negligible
  Left Company Last Year            +0.099   Negligible
  Absenteeism (days/month)          +0.066   Negligible
  Years in Company                  +0.039   Negligible
  Years Since Last Promotion        +0.031   Negligible
  Age                               +0.015   Negligible
  Social Support                    -0.022   Negligible
  Vacation Days Taken               -0.050   Negligible
  Manager Support                   -0.086   Negligible
  Job Satisfaction                  -0.143      Weak
  Sleep Quality                     -0.234    Moderate
  Work-Life Balance                 -0.310    Moderate

╭─────────────────────────────────────────────── 📊 Key Takeaways ────────────────────────────────────────────────╮
│ Strongest Risk Factor: Stress Level (self-report) (+0.480)                                                      │
│ Strongest Protective Factor: Work-Life Balance (-0.310)                                                         │
│ Top 3 Risk Drivers: Stress Level (self-report), Workload Index, Hours Worked per Week                           │
│ Top 3 Protective Factors: Job Satisfaction, Sleep Quality, Work-Life Balance                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Saved HTML report

In [15]:



COLOR_DARK_NAVY = "#333F6E"
COLOR_BLUE_GREY = "#869EAF"

COLOR_GREEN = "#A1E197"      # higher nonlinear association
COLOR_RED = "#E08D8D"        # lower nonlinear association
COLOR_YELLOW = "#E8D58B"     # moderate association

HTML_OUTPUT_PATH = "Report/burnout_nonlinear_analysis.html"



console = Console(record=True)


target_encoder = LabelEncoder()

y = target_encoder.fit_transform(data["burnout_risk"])

 

numeric_cols = data.select_dtypes(include="number").columns.tolist()

excluded_cols = [
    "employee_id",
    "burnout_risk_numeric"
]

numeric_cols = [
    col for col in numeric_cols
    if col not in excluded_cols
]


X = data[numeric_cols].copy()


X = X.replace([np.inf, -np.inf], np.nan)

X = X.fillna(X.median())


mi_scores = mutual_info_classif(
    X,
    y,
    random_state=42
)

mi_results = pd.Series(
    mi_scores,
    index=numeric_cols
).sort_values(ascending=False)


 

LABELS = {
    "stress_level_self_report": "Stress Level (self-report)",
    "workload_index": "Workload Index",
    "hours_worked_per_week": "Hours Worked per Week",
    "overtime_hours_per_week": "Overtime (hrs/week)",
    "anxiety_score": "Anxiety Score",
    "depression_score": "Depression Score",
    "monthly_salary_usd": "Monthly Salary",
    "commute_time_mins": "Commute Time",
    "presenteeism_days_per_month": "Presenteeism (days/month)",
    "mental_health_benefit_utilized": "Mental Health Benefit Used",
    "left_company_last_year": "Left Company Last Year",
    "absenteeism_days_per_month": "Absenteeism (days/month)",
    "years_in_company": "Years in Company",
    "years_since_last_promotion": "Years Since Last Promotion",
    "age": "Age",
    "social_support_score": "Social Support",
    "vacation_days_taken": "Vacation Days Taken",
    "manager_support_score": "Manager Support",
    "job_satisfaction_score": "Job Satisfaction",
    "sleep_quality_score": "Sleep Quality",
    "work_life_balance_score": "Work-Life Balance",
}


 

def nonlinear_strength(value: float) -> str:

    if value >= 0.30:
        return "Strong"

    if value >= 0.15:
        return "Moderate"

    if value >= 0.05:
        return "Weak"

    return "Negligible"


def strength_color(value: float) -> str:

    if value >= 0.30:
        return COLOR_GREEN

    if value >= 0.15:
        return COLOR_YELLOW

    return COLOR_RED
 

mi_table = Table(
    title="🧠 Nonlinear Relationship with Burnout Risk",
    box=box.SIMPLE,
    header_style=f"bold {COLOR_DARK_NAVY}"
)

mi_table.add_column(
    "Factor",
    style=COLOR_BLUE_GREY
)

mi_table.add_column(
    "Mutual Information",
    justify="right"
)

mi_table.add_column(
    "Nonlinear Association",
    justify="center"
)


for col, value in mi_results.items():

    label = LABELS.get(col, col)

    color = strength_color(value)

    mi_table.add_row(
        label,
        f"[{color}]{value:.3f}[/{color}]",
        nonlinear_strength(value)
    )


console.print(mi_table)


 

top_factor = mi_results.index[0]
second_factor = mi_results.index[1]
third_factor = mi_results.index[2]

weakest_factor = mi_results.index[-1]


console.print(
    Panel(
        f"[bold {COLOR_GREEN}]Strongest Nonlinear Driver:[/bold {COLOR_GREEN}] "
        f"{LABELS.get(top_factor, top_factor)} "
        f"({mi_results[top_factor]:.3f})\n"

        f"[bold {COLOR_YELLOW}]Other Important Nonlinear Factors:[/bold {COLOR_YELLOW}] "
        f"{LABELS.get(second_factor, second_factor)}, "
        f"{LABELS.get(third_factor, third_factor)}\n"

        f"[bold {COLOR_RED}]Weakest Nonlinear Relationship:[/bold {COLOR_RED}] "
        f"{LABELS.get(weakest_factor, weakest_factor)} "
        f"({mi_results[weakest_factor]:.3f})\n"

        f"[bold {COLOR_BLUE_GREY}]Top 5 Nonlinear Drivers:[/bold {COLOR_BLUE_GREY}] "
        + ", ".join(
            LABELS.get(col, col)
            for col in mi_results.head(5).index
        ),

        title="📊 Key Takeaways",
        border_style=COLOR_DARK_NAVY
    )
)


 

console.print(
    Panel(
        "\n".join(
            f"{i}. {LABELS.get(col, col)} "
            f"({value:.3f})"
            for i, (col, value)
            in enumerate(mi_results.head(10).items(), start=1)
        ),
        title="🔍 Top 10 Nonlinear Relationships",
        border_style=COLOR_DARK_NAVY
    )
)

 

console.save_html(
    HTML_OUTPUT_PATH,
    theme=None,
    inline_styles=True
)

 

with open(HTML_OUTPUT_PATH, "r", encoding="utf-8") as f:
    html_content = f.read()


html_content = html_content.replace(
    "body {\n    color: #000000;\n    background-color: #ffffff;\n}",
    f"""
    body {{
        color: {COLOR_BLUE_GREY};
        background-color: #000000;
    }}
    """
)


html_content = html_content.replace(
    "<body>",
    '<body style="background-color:#000000; margin:0; padding:20px;">'
)


with open(HTML_OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(html_content)


print(f"\nSaved HTML report")

                🧠 Nonlinear Relationship with Burnout Risk

  Factor                       Mutual Information   Nonlinear Association
 ─────────────────────────────────────────────────────────────────────────
  Stress Level (self-report)                0.135           Weak
  Workload Index                            0.110           Weak
  Hours Worked per Week                     0.088           Weak
  Work-Life Balance                         0.049        Negligible
  Overtime (hrs/week)                       0.047        Negligible
  Anxiety Score                             0.037        Negligible
  Sleep Quality                             0.027        Negligible
  Depression Score                          0.012        Negligible
  Manager Support                           0.010        Negligible
  Job Satisfaction                          0.010        Negligible
  Monthly Salary                            0.006        Negligible
  Social Support                            0.006        Negligible
  Mental Health Benefit Used                0.006        Negligible
  Commute Time                              0.006        Negligible
  Years in Company                          0.003        Negligible
  Left Company Last Year                    0.003        Negligible
  Years Since Last Promotion                0.002        Negligible
  Absenteeism (days/month)                  0.001        Negligible
  Presenteeism (days/month)                 0.001        Negligible
  Age                                       0.000        Negligible
  Vacation Days Taken                       0.000        Negligible

╭─────────────────────────────────────────────── 📊 Key Takeaways ────────────────────────────────────────────────╮
│ Strongest Nonlinear Driver: Stress Level (self-report) (0.135)                                                  │
│ Other Important Nonlinear Factors: Workload Index, Hours Worked per Week                                        │
│ Weakest Nonlinear Relationship: Vacation Days Taken (0.000)                                                     │
│ Top 5 Nonlinear Drivers: Stress Level (self-report), Workload Index, Hours Worked per Week, Work-Life Balance,  │
│ Overtime (hrs/week)                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────── 🔍 Top 10 Nonlinear Relationships ───────────────────────────────────────╮
│ 1. Stress Level (self-report) (0.135)                                                                           │
│ 2. Workload Index (0.110)                                                                                       │
│ 3. Hours Worked per Week (0.088)                                                                                │
│ 4. Work-Life Balance (0.049)                                                                                    │
│ 5. Overtime (hrs/week) (0.047)                                                                                  │
│ 6. Anxiety Score (0.037)                                                                                        │
│ 7. Sleep Quality (0.027)                                                                                        │
│ 8. Depression Score (0.012)                                                                                     │
│ 9. Manager Support (0.010)                                                                                      │
│ 10. Job Satisfaction (0.010)                                                                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Saved HTML report

In [16]:
data.sample()

,employee_id,age,gender,role,years_in_company,hours_worked_per_week,work_life_balance_score,job_satisfaction_score,stress_level_self_report,anxiety_score,depression_score,sleep_quality_score,social_support_score,presenteeism_days_per_month,burnout_risk,left_company_last_year,work_mode,commute_time_mins,monthly_salary_usd,manager_support_score,workload_index,vacation_days_taken,years_since_last_promotion,absenteeism_days_per_month,overtime_hours_per_week,mental_health_benefit_utilized,Age_group,burnout_risk_numeric
21860,21861,33,Female,Manager,10,49,3.3,4.5,2.7,4.5,6.1,2.7,2.2,4,Moderate,0,Hybrid,14,8350.0,3.5,5.5,16,10.0,1,0,0,30-39,1

In [17]:
data['hours_worked_per_week'].agg(['min', 'mean', 'max']).round(1)

min     35.0
mean    46.2
max     70.0
Name: hours_worked_per_week, dtype: float64

In [18]:
bins = [30, 40, 50, 60, 100]
labels = ['30-39', '40-49', '50-59', '60+']
data['hours_worked_group'] = pd.cut(data['hours_worked_per_week'], bins=bins, labels=labels, right=False)

In [25]:
risk_summary = (
    data
    .groupby("hours_worked_group", observed=True)
    .agg(
        Employees=("employee_id", "count"),
        Avg_Hours=("hours_worked_per_week", "mean")
    )
)

risk_percentage = (
    data
    .groupby("hours_worked_group", observed=True)["burnout_risk"]
    .value_counts(normalize=True)
    .unstack(fill_value=0)
    .mul(100)
    .round(1)
)

risk_summary = risk_summary.join(risk_percentage)

risk_summary

                    Employees  Avg_Hours  High   Low  Moderate
hours_worked_group
30-39                    3033  37.209034   2.3  43.5      54.2
40-49                   15100  44.890596  11.4  18.8      69.8
50-59                    6673  52.695339  31.5   5.1      63.4
60+                       194  61.453608  57.7   0.0      42.3

In [27]:
HTML_OUTPUT_PATH = "Report/burnout_risk_by_working_hours.html"

COLOR_DARK_NAVY = "#333F6E"
COLOR_BLUE_GREY = "#869EAF"

COLOR_LOW = "#A1E197"
COLOR_MODERATE = "#E8D58B"
COLOR_HIGH = "#E08D8D"


styled_summary = risk_summary.copy()

format_dict = {
    "Employees": "{:,.0f}",
    "Avg_Hours": "{:.1f}",
}

for col in ["Low", "Moderate", "High"]:
    if col in styled_summary.columns:
        format_dict[col] = "{:.1f}%"


def color_risk_cell(value, risk_type):
    intensity = min(max(float(value) / 60, 0), 1)

    if risk_type == "High":
        return (
            f"background-color: rgba(224, 141, 141, {0.15 + intensity * 0.75});"
            f"color: #FFFFFF;"
            f"font-weight: bold;"
        )

    elif risk_type == "Moderate":
        return (
            f"background-color: rgba(232, 213, 139, {0.15 + intensity * 0.55});"
            f"color: #111111;"
        )

    elif risk_type == "Low":
        return (
            f"background-color: rgba(161, 225, 151, {0.15 + intensity * 0.65});"
            f"color: #111111;"
        )

    return ""


def style_risk_columns(row):

    styles = pd.Series("", index=row.index)

    for risk_type in ["Low", "Moderate", "High"]:

        if risk_type in row.index:

            styles[risk_type] = color_risk_cell(
                row[risk_type],
                risk_type
            )

    return styles


styled_summary = (
    styled_summary
    .style
    .format(format_dict)
    .apply(style_risk_columns, axis=1)
)


table_html = styled_summary.to_html(
    border=0,
    justify="center",
    classes="risk-table"
)


html_content = f"""
<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<title>Burnout Risk by Working Hours</title>

<style>

body {{
    background-color: #000000;
    color: #FFFFFF;
    font-family: Arial, sans-serif;
    padding: 40px;
}}

h1 {{
    color: {COLOR_LOW};
    text-align: center;
    margin-bottom: 8px;
}}

.description {{
    color: {COLOR_BLUE_GREY};
    text-align: center;
    margin-bottom: 30px;
}}

.table-container {{
    max-width: 1100px;
    margin: auto;
    overflow-x: auto;
}}

table {{
    width: 100%;
    border-collapse: collapse;
    background-color: #111111;
}}

th {{
    background-color: {COLOR_DARK_NAVY};
    color: #FFFFFF;
    padding: 14px;
    text-align: center;
    border-bottom: 2px solid {COLOR_BLUE_GREY};
}}

td {{
    padding: 12px;
    text-align: center;
    border-bottom: 1px solid #333333;
}}

tr:hover td {{
    filter: brightness(1.15);
}}

</style>

</head>


<body>

<h1>Burnout Risk by Working Hours</h1>

<div class="description">
    Burnout risk distribution across weekly working-hour groups
</div>

<div class="table-container">

{table_html}

</div>

</body>

</html>
"""


with open(HTML_OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(html_content)


print(f"Saved HTML report ")

Saved HTML report

In [28]:
data.sample()

,employee_id,age,gender,role,years_in_company,hours_worked_per_week,work_life_balance_score,job_satisfaction_score,stress_level_self_report,anxiety_score,depression_score,sleep_quality_score,social_support_score,presenteeism_days_per_month,burnout_risk,left_company_last_year,work_mode,commute_time_mins,monthly_salary_usd,manager_support_score,workload_index,vacation_days_taken,years_since_last_promotion,absenteeism_days_per_month,overtime_hours_per_week,mental_health_benefit_utilized,Age_group,burnout_risk_numeric,hours_worked_group
21108,21109,43,Male,Sales,13,43,3.7,4.4,1.7,3.4,0.7,4.5,2.9,0,High,0,Remote,0,7600.0,2.6,6.9,15,9.0,2,0,0,40-49,2,40-49

In [30]:
 
HTML_OUTPUT_PATH = "Report/burnout_risk_by_employee_profile.html"
 


# =========================
# Colors
# =========================
COLOR_DARK_NAVY = "#333F6E"
COLOR_BLUE_GREY = "#869EAF"

COLOR_LOW = "#A1E197"
COLOR_MODERATE = "#E8D58B"
COLOR_HIGH = "#E08D8D"


# =========================
# Variables
# =========================
variables = {
    "role": "Burnout Risk by Role",
    "gender": "Burnout Risk by Gender",
    "work_mode": "Burnout Risk by Work Mode"
}


# =========================
# Create tables
# =========================
tables_html = []

for column, title in variables.items():

    summary = (
        data.groupby(column, observed=True)["burnout_risk"]
        .value_counts(normalize=True)
        .unstack(fill_value=0)
        .mul(100)
        .round(1)
    )

    # Make sure all risk columns exist
    for risk in ["Low", "Moderate", "High"]:
        if risk not in summary.columns:
            summary[risk] = 0

    summary = summary[["Low", "Moderate", "High"]]

    # Employee count
    employee_count = (
        data.groupby(column, observed=True)
        .size()
        .rename("Employees")
    )

    summary = employee_count.to_frame().join(summary)

    # =========================
    # Formatting
    # =========================
    format_dict = {
        "Employees": "{:,.0f}",
        "Low": "{:.1f}%",
        "Moderate": "{:.1f}%",
        "High": "{:.1f}%"
    }


    # =========================
    # Risk cell colors
    # =========================
    def color_risk_cell(value, risk_type):

        value = float(value)

        # Percentage → color intensity
        intensity = min(max(value / 60, 0), 1)

        if risk_type == "High":
            return (
                f"background-color: rgba(224, 141, 141, "
                f"{0.15 + intensity * 0.75});"
                "color: #FFFFFF;"
                "font-weight: bold;"
            )

        elif risk_type == "Moderate":
            return (
                f"background-color: rgba(232, 213, 139, "
                f"{0.15 + intensity * 0.55});"
                "color: #111111;"
            )

        elif risk_type == "Low":
            return (
                f"background-color: rgba(161, 225, 151, "
                f"{0.15 + intensity * 0.65});"
                "color: #111111;"
            )

        return ""


    def style_risk_columns(row):

        styles = pd.Series("", index=row.index)

        for risk_type in ["Low", "Moderate", "High"]:

            if risk_type in row.index:
                styles[risk_type] = color_risk_cell(
                    row[risk_type],
                    risk_type
                )

        return styles


    styled_table = (
        summary
        .style
        .format(format_dict)
        .apply(style_risk_columns, axis=1)
    )

    table_html = styled_table.to_html(
        border=0,
        justify="center",
        classes="risk-table"
    )

    tables_html.append(
        f"""
        <section class="analysis-section">

            <h2>{title}</h2>

            <div class="table-container">
                {table_html}
            </div>

        </section>
        """
    )


# =========================
# Final HTML
# =========================
html_content = f"""
<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<title>Burnout Risk by Employee Profile</title>

<style>

body {{
    background-color: #000000;
    color: #FFFFFF;
    font-family: Arial, sans-serif;
    padding: 40px;
}}

h1 {{
    color: {COLOR_LOW};
    text-align: center;
    margin-bottom: 10px;
}}

.description {{
    color: {COLOR_BLUE_GREY};
    text-align: center;
    margin-bottom: 45px;
}}

.analysis-section {{
    max-width: 1100px;
    margin: 0 auto 50px auto;
}}

h2 {{
    color: #FFFFFF;
    margin-bottom: 15px;
    border-left: 5px solid {COLOR_BLUE_GREY};
    padding-left: 12px;
}}

.table-container {{
    overflow-x: auto;
}}

table {{
    width: 100%;
    border-collapse: collapse;
    background-color: #111111;
}}

th {{
    background-color: {COLOR_DARK_NAVY};
    color: #FFFFFF;
    padding: 14px;
    text-align: center;
    border-bottom: 2px solid {COLOR_BLUE_GREY};
}}

td {{
    padding: 12px;
    text-align: center;
    border-bottom: 1px solid #333333;
}}

tr:hover td {{
    filter: brightness(1.15);
}}

</style>

</head>


<body>

<h1>Burnout Risk by Employee Profile</h1>

<div class="description">

Burnout risk distribution across role, gender, and work mode

</div>

{''.join(tables_html)}

</body>

</html>
"""


# =========================
# Save
# =========================
with open(HTML_OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(html_content)

print(f"Saved HTML report")

Saved HTML report

In [31]:
data.sample()

,employee_id,age,gender,role,years_in_company,hours_worked_per_week,work_life_balance_score,job_satisfaction_score,stress_level_self_report,anxiety_score,depression_score,sleep_quality_score,social_support_score,presenteeism_days_per_month,burnout_risk,left_company_last_year,work_mode,commute_time_mins,monthly_salary_usd,manager_support_score,workload_index,vacation_days_taken,years_since_last_promotion,absenteeism_days_per_month,overtime_hours_per_week,mental_health_benefit_utilized,Age_group,burnout_risk_numeric,hours_worked_group
23781,23782,33,Female,Developer,8,44,4.5,3.2,1.6,4.6,3.0,3.8,4.1,0,Moderate,0,On-site,78,6550.0,4.1,2.1,20,2.0,1,0,0,30-39,1,40-49

In [32]:
HTML_OUTPUT_PATH = "Report/burnout_risk_by_company_support.html"


COLOR_DARK_NAVY = "#333F6E"
COLOR_BLUE_GREY = "#869EAF"

COLOR_LOW = "#A1E197"
COLOR_MODERATE = "#E8D58B"
COLOR_HIGH = "#E08D8D"


variables = {
    "left_company_last_year": "Burnout Risk by Employee Turnover",
    "mental_health_benefit_utilized": "Burnout Risk by Mental Health Benefit Usage"
}


tables_html = []

for column, title in variables.items():

    summary = (
        data.groupby(column, observed=True)["burnout_risk"]
        .value_counts(normalize=True)
        .unstack(fill_value=0)
        .mul(100)
        .round(1)
    )

    for risk in ["Low", "Moderate", "High"]:
        if risk not in summary.columns:
            summary[risk] = 0

    summary = summary[["Low", "Moderate", "High"]]

    employee_count = (
        data.groupby(column, observed=True)
        .size()
        .rename("Employees")
    )

    summary = employee_count.to_frame().join(summary)


    format_dict = {
        "Employees": "{:,.0f}",
        "Low": "{:.1f}%",
        "Moderate": "{:.1f}%",
        "High": "{:.1f}%"
    }


    def color_risk_cell(value, risk_type):

        value = float(value)

        intensity = min(max(value / 60, 0), 1)

        if risk_type == "High":
            return (
                f"background-color: rgba(224, 141, 141, "
                f"{0.15 + intensity * 0.75});"
                "color: #FFFFFF;"
                "font-weight: bold;"
            )

        elif risk_type == "Moderate":
            return (
                f"background-color: rgba(232, 213, 139, "
                f"{0.15 + intensity * 0.55});"
                "color: #111111;"
            )

        elif risk_type == "Low":
            return (
                f"background-color: rgba(161, 225, 151, "
                f"{0.15 + intensity * 0.65});"
                "color: #111111;"
            )

        return ""


    def style_risk_columns(row):

        styles = pd.Series("", index=row.index)

        for risk_type in ["Low", "Moderate", "High"]:

            if risk_type in row.index:
                styles[risk_type] = color_risk_cell(
                    row[risk_type],
                    risk_type
                )

        return styles


    styled_table = (
        summary
        .style
        .format(format_dict)
        .apply(style_risk_columns, axis=1)
    )

    table_html = styled_table.to_html(
        border=0,
        justify="center",
        classes="risk-table"
    )

    tables_html.append(
        f"""
        <section class="analysis-section">

            <h2>{title}</h2>

            <div class="table-container">
                {table_html}
            </div>

        </section>
        """
    )


html_content = f"""
<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<title>Burnout Risk by Company & Mental Health Support</title>

<style>

body {{
    background-color: #000000;
    color: #FFFFFF;
    font-family: Arial, sans-serif;
    padding: 40px;
}}

h1 {{
    color: {COLOR_LOW};
    text-align: center;
    margin-bottom: 10px;
}}

.description {{
    color: {COLOR_BLUE_GREY};
    text-align: center;
    margin-bottom: 45px;
}}

.analysis-section {{
    max-width: 1100px;
    margin: 0 auto 50px auto;
}}

h2 {{
    color: #FFFFFF;
    margin-bottom: 15px;
    border-left: 5px solid {COLOR_BLUE_GREY};
    padding-left: 12px;
}}

.table-container {{
    overflow-x: auto;
}}

table {{
    width: 100%;
    border-collapse: collapse;
    background-color: #111111;
}}

th {{
    background-color: {COLOR_DARK_NAVY};
    color: #FFFFFF;
    padding: 14px;
    text-align: center;
    border-bottom: 2px solid {COLOR_BLUE_GREY};
}}

td {{
    padding: 12px;
    text-align: center;
    border-bottom: 1px solid #333333;
}}

tr:hover td {{
    filter: brightness(1.15);
}}

</style>

</head>


<body>

<h1>Burnout Risk by Company & Mental Health Support</h1>

<div class="description">

Burnout risk distribution by employee turnover and mental health benefit utilization

</div>

{''.join(tables_html)}

</body>

</html>
"""


with open(HTML_OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(html_content)

print(f"Saved HTML report")

Saved HTML report

In [33]:
data['years_in_company'].agg(['min', 'mean', 'max']).round(1)

min      0.0
mean     9.0
max     42.0
Name: years_in_company, dtype: float64

In [34]:
data['monthly_salary_usd'].agg(['min', 'mean', 'max']).round(1)

min      2500.0
mean     8181.1
max     19450.0
Name: monthly_salary_usd, dtype: float64

In [36]:
HTML_OUTPUT_PATH = "Report/burnout_risk_by_tenure_salary.html"


COLOR_DARK_NAVY = "#333F6E"
COLOR_BLUE_GREY = "#869EAF"

COLOR_LOW = "#A1E197"
COLOR_MODERATE = "#E8D58B"
COLOR_HIGH = "#E08D8D"


data["years_in_company_group"] = pd.cut(
    data["years_in_company"],
    bins=[-1, 2, 5, 8, 11, 14, float("inf")],
    labels=[
        "0–2 years",
        "3–5 years",
        "6–8 years",
        "9–11 years",
        "12–14 years",
        "15+ years"
    ]
)


salary_min = data["monthly_salary_usd"].min()
salary_max = data["monthly_salary_usd"].max()

salary_bins = pd.qcut(
    data["monthly_salary_usd"],
    q=5,
    duplicates="drop"
)

data["salary_group"] = salary_bins


variables = {
    "years_in_company_group": "Burnout Risk by Years in Company",
    "salary_group": "Burnout Risk by Monthly Salary"
}


tables_html = []


for column, title in variables.items():

    summary = (
        data.groupby(column, observed=True)["burnout_risk"]
        .value_counts(normalize=True)
        .unstack(fill_value=0)
        .mul(100)
        .round(1)
    )

    for risk in ["Low", "Moderate", "High"]:
        if risk not in summary.columns:
            summary[risk] = 0

    summary = summary[["Low", "Moderate", "High"]]


    employee_count = (
        data.groupby(column, observed=True)
        .size()
        .rename("Employees")
    )

    summary = employee_count.to_frame().join(summary)


    format_dict = {
        "Employees": "{:,.0f}",
        "Low": "{:.1f}%",
        "Moderate": "{:.1f}%",
        "High": "{:.1f}%"
    }


    def color_risk_cell(value, risk_type):

        value = float(value)

        intensity = min(max(value / 60, 0), 1)

        if risk_type == "High":

            return (
                f"background-color: rgba(224, 141, 141, "
                f"{0.15 + intensity * 0.75});"
                "color: #FFFFFF;"
                "font-weight: bold;"
            )

        elif risk_type == "Moderate":

            return (
                f"background-color: rgba(232, 213, 139, "
                f"{0.15 + intensity * 0.55});"
                "color: #111111;"
            )

        elif risk_type == "Low":

            return (
                f"background-color: rgba(161, 225, 151, "
                f"{0.15 + intensity * 0.65});"
                "color: #111111;"
            )

        return ""


    def style_risk_columns(row):

        styles = pd.Series("", index=row.index)

        for risk_type in ["Low", "Moderate", "High"]:

            if risk_type in row.index:

                styles[risk_type] = color_risk_cell(
                    row[risk_type],
                    risk_type
                )

        return styles


    styled_table = (
        summary
        .style
        .format(format_dict)
        .apply(style_risk_columns, axis=1)
    )


    table_html = styled_table.to_html(
        border=0,
        justify="center",
        classes="risk-table"
    )


    tables_html.append(
        f"""
        <section class="analysis-section">

            <h2>{title}</h2>

            <div class="table-container">
                {table_html}
            </div>

        </section>
        """
    )


html_content = f"""
<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<title>Burnout Risk by Tenure & Salary</title>

<style>

body {{
    background-color: #000000;
    color: #FFFFFF;
    font-family: Arial, sans-serif;
    padding: 40px;
}}

h1 {{
    color: {COLOR_LOW};
    text-align: center;
    margin-bottom: 10px;
}}

.description {{
    color: {COLOR_BLUE_GREY};
    text-align: center;
    margin-bottom: 45px;
}}

.analysis-section {{
    max-width: 1100px;
    margin: 0 auto 50px auto;
}}

h2 {{
    color: #FFFFFF;
    margin-bottom: 15px;
    border-left: 5px solid {COLOR_BLUE_GREY};
    padding-left: 12px;
}}

.table-container {{
    overflow-x: auto;
}}

table {{
    width: 100%;
    border-collapse: collapse;
    background-color: #111111;
}}

th {{
    background-color: {COLOR_DARK_NAVY};
    color: #FFFFFF;
    padding: 14px;
    text-align: center;
    border-bottom: 2px solid {COLOR_BLUE_GREY};
}}

td {{
    padding: 12px;
    text-align: center;
    border-bottom: 1px solid #333333;
}}

tr:hover td {{
    filter: brightness(1.15);
}}

</style>

</head>


<body>

<h1>Burnout Risk by Tenure & Salary</h1>

<div class="description">

Burnout risk distribution across employee tenure and monthly salary groups

</div>

{''.join(tables_html)}

</body>

</html>
"""


with open(HTML_OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(html_content)

print(f"Saved HTML report")

Saved HTML report